#!/bin/sh
# Prints the Homebrew formula for a release. The release workflow commits the
# output to the Jleagle/homebrew-tilt-admin tap as Formula/tilt-admin.rb, where
# brew compiles it from the tagged source on the user's machine.
#
#   formula.sh <version> <sha256-of-source-tarball>
set -eu

VERSION="$1"
SHA256="$2"

case "$VERSION" in
  *[!0-9.]*|.*|*.|"") echo "formula.sh: bad version '$VERSION' (expected e.g. 1.2.3)" >&2; exit 1 ;;
esac

cat <<FORMULA
# Generated by homebrew/formula.sh in Jleagle/tilt-admin on each release. DO NOT EDIT.
class TiltAdmin < Formula
  desc "Native macOS app for managing Tilt dev services"
  homepage "https://github.com/Jleagle/tilt-admin"
  url "https://github.com/Jleagle/tilt-admin/archive/refs/tags/v${VERSION}.tar.gz"
  sha256 "${SHA256}"

  livecheck do
    skip "Updated by the release workflow."
  end

  # SwiftUI's macros ship with Xcode only, so the Command Line Tools cannot
  # build this. Package.swift targets macOS 15, which Xcode 16 is the first to
  # have an SDK for.
  depends_on xcode: ["16.0", :build]
  depends_on macos: :sequoia

  def install
    system "swift", "build", *std_swift_args

    # The app loads its icon through Bundle.module, which looks for the
    # resource bundle beside the executable as it was invoked, without
    # resolving symlinks. Keep the binary and bundle together in libexec and
    # put a wrapper script in bin, not a symlink.
    libexec.install ".build/release/TiltAdmin_TiltAdmin.bundle",
                    ".build/release/TiltAdmin" => "tilt-admin"
    bin.write_exec_script libexec/"tilt-admin"
  end

  def caveats
    <<~EOS
      tilt-admin needs a config describing your Tilt service dependencies.
      Create one at ~/.tilt-admin.yml — see
      https://github.com/Jleagle/tilt-admin#configuration
    EOS
  end

  test do
    # Without the resource bundle the app aborts on launch. Where the icon sits
    # inside the bundle depends on the SwiftPM build system that produced it.
    refute_empty Dir.glob(libexec/"TiltAdmin_TiltAdmin.bundle/**/AppIcon.icns")
  end
end
FORMULA
